layout: page
title: "stuff"
permalink: https://nicolopedrani.github.io

title: Nicolo Pedrani homepage
description: Phd Student at IIT

markdown: kramdown

header_pages:
  - index.html

plugins:
  - jemoji

show_excerpts: true
google_analytics: UA-NNNNNNNN-N