layout: page
theme: jekyll-theme-leap-day
title: "stuff"
permalink: https://nicolopedrani.github.io

theme: jekyll-theme-leap-day
title: Nicolo Pedrani homepage
description: Phd Student at IIT

markdown: kramdown

header_pages:
  - README.md

plugins:
  - jemoji

show_excerpts: true
google_analytics: UA-NNNNNNNN-N